// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTTaTbVIg_cMfYq4U_eiOptVsWbsLaHGk',
    appId: '1:342028777346:web:33ef3cb501c1d450eb419b',
    messagingSenderId: '342028777346',
    projectId: 'khata-71406',
    authDomain: 'khata-71406.firebaseapp.com',
    storageBucket: 'khata-71406.firebasestorage.app',
    measurementId: 'G-VQ6S52M3JN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRRaefzVDpYr4SJCZAGvYxhOUhWYwdoWA',
    appId: '1:342028777346:android:74aef80e053fc015eb419b',
    messagingSenderId: '342028777346',
    projectId: 'khata-71406',
    storageBucket: 'khata-71406.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHXdQ5HibIMxCCae6_9wAO2SPHCGjKklQ',
    appId: '1:342028777346:ios:ba83a05c9713ad56eb419b',
    messagingSenderId: '342028777346',
    projectId: 'khata-71406',
    storageBucket: 'khata-71406.firebasestorage.app',
    androidClientId: '342028777346-tqght9b8v8tm1eahi9onr3ho2mrmg8fe.apps.googleusercontent.com',
    iosClientId: '342028777346-1f4q7c6leno0qdh5eprhqb14h0ce0ive.apps.googleusercontent.com',
    iosBundleId: 'com.example.khata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHXdQ5HibIMxCCae6_9wAO2SPHCGjKklQ',
    appId: '1:342028777346:ios:ba83a05c9713ad56eb419b',
    messagingSenderId: '342028777346',
    projectId: 'khata-71406',
    storageBucket: 'khata-71406.firebasestorage.app',
    androidClientId: '342028777346-tqght9b8v8tm1eahi9onr3ho2mrmg8fe.apps.googleusercontent.com',
    iosClientId: '342028777346-1f4q7c6leno0qdh5eprhqb14h0ce0ive.apps.googleusercontent.com',
    iosBundleId: 'com.example.khata',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTTaTbVIg_cMfYq4U_eiOptVsWbsLaHGk',
    appId: '1:342028777346:web:1742a57d34873286eb419b',
    messagingSenderId: '342028777346',
    projectId: 'khata-71406',
    authDomain: 'khata-71406.firebaseapp.com',
    storageBucket: 'khata-71406.firebasestorage.app',
    measurementId: 'G-LQSHLJDVV7',
  );
}
